version: "3.9"

networks:
  dev:
    driver: bridge

services:
  logging-service:
    depends_on:
      - "proceedix_db"
    container_name: logging-service
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionString="Host=localhost; Database=proceedix-logging; Port=5432; Username=proceedix; Password=proceedix"
    networks:
      - dev

  proceedix_db:
    image: postgres:latest
    container_name: proceedix_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - POSTGRES_DB=proceedix-logging
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=proceedix
      - POSTGRES_PASSWORD=proceedix
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dev
